import { and, eq } from "drizzle-orm";
import type { Context } from "hono";
import type { z } from "zod";
import { conversations } from "../db/schema";
import type { Bindings, Variables } from "../types";

export type AppContext = Context<{ Bindings: Bindings; Variables: Variables }>;

/**
 * Shape check for nanoid-based resource IDs (e.g. conversation IDs).
 * Nanoid's default alphabet is URL-safe: letters, digits, hyphens, and
 * underscores. This intentionally does not enforce the exact 21-char length
 * generated by `generateId()` — only the character set and a sane length
 * range — so that well-formed-but-nonexistent IDs still fall through to a
 * 404 rather than a 400.
 */
const RESOURCE_ID_PATTERN = /^[A-Za-z0-9_-]{1,255}$/;

/**
 * Returns true if `id` has the shape of a valid resource ID (nanoid-style).
 * Does not check whether the resource actually exists.
 */
export function isValidResourceId(id: string): boolean {
  return RESOURCE_ID_PATTERN.test(id);
}

/**
 * Return a standard 400 error for a malformed resource ID (e.g. containing
 * invalid characters, or empty/too long), as opposed to a well-formed ID
 * that simply doesn't match an existing resource (which should be a 404).
 */
export function invalidId(c: AppContext, message = "Invalid id") {
  return c.json({ error: { code: "BAD_REQUEST", message } }, 400);
}

/**
 * Parse and validate a limit query parameter with configurable bounds.
 *
 * @param raw - The raw string value from query parameter (undefined if not provided)
 * @param defaultLimit - The default limit to use if parameter is missing or invalid (default: 50)
 * @param maxLimit - The maximum allowed limit (default: 100)
 * @returns A validated limit between 1 and maxLimit, or defaultLimit if invalid
 *
 * @example
 * ```ts
 * const limit = parseLimitParam(c.req.query("limit")); // defaults to 50, max 100
 * const limit = parseLimitParam(c.req.query("limit"), 20, 200); // custom defaults
 * ```
 */
export function parseLimitParam(
  raw: string | undefined,
  defaultLimit: number = 50,
  maxLimit: number = 100,
): number {
  const limitRaw = parseInt(raw ?? String(defaultLimit), 10);
  return Math.min(Number.isNaN(limitRaw) || limitRaw < 1 ? defaultLimit : limitRaw, maxLimit);
}

/**
 * Load a conversation that belongs to the authenticated project.
 * Returns the conversation row or null if not found / wrong project.
 */
export async function loadConversation(c: AppContext, id: string) {
  const db = c.get("db");
  const projectId = c.get("projectId");

  const [conv] = await db
    .select()
    .from(conversations)
    .where(and(eq(conversations.id, id), eq(conversations.projectId, projectId)))
    .limit(1);

  return conv ?? null;
}

/**
 * Return a standard 400 error for invalid JSON body.
 */
export function badRequest(c: AppContext, message = "Invalid JSON body") {
  return c.json({ error: { code: "BAD_REQUEST", message } }, 400);
}

/**
 * Parse JSON body from request, returning null on invalid JSON.
 */
export async function parseJsonBody(c: AppContext) {
  const body = await c.req.json().catch(() => null);
  if (body === null) {
    return { body: null, error: badRequest(c) } as const;
  }
  return { body, error: null } as const;
}

/**
 * Return a standard 400 error for Zod validation failures.
 */
export function validationError(c: AppContext, zodError: z.ZodError) {
  return c.json(
    { error: { code: "BAD_REQUEST", message: zodError.issues[0]?.message ?? "Validation error" } },
    400,
  );
}

/**
 * Return a standard 404 error.
 */
export function notFound(c: AppContext, message = "Conversation not found") {
  return c.json({ error: { code: "NOT_FOUND", message } }, 404);
}

/**
 * Return a generic error response with custom code, message, and status.
 */
export function errorResponse(
  c: AppContext,
  code: string,
  message: string,
  status: 400 | 401 | 403 | 404 | 409 | 429 | 500 = 500,
) {
  return c.json({ error: { code, message } }, status);
}

/**
 * Verify the requested project ID matches the authenticated project ID.
 * Returns a 403 response if they don't match, or null if authorized.
 */
export function requireSameProject(c: AppContext, projectId: string) {
  const authedProjectId = c.get("projectId");
  if (projectId !== authedProjectId) {
    return c.json(
      { error: { code: "FORBIDDEN", message: "Cannot manage keys for another project" } },
      403,
    );
  }
  return null;
}

/**
 * Parse JSON body and validate against a Zod schema.
 * Returns the validated data or an error response.
 */
export async function parseAndValidateBody<T extends z.ZodType>(
  c: AppContext,
  schema: T,
): Promise<{ data: z.infer<T> | null; error: Response | null }> {
  const { body, error } = await parseJsonBody(c);
  if (error) return { data: null, error };

  const parsed = schema.safeParse(body);
  if (!parsed.success) return { data: null, error: validationError(c, parsed.error) };

  return { data: parsed.data, error: null };
}

/**
 * Invalidate auth-cache entries for the given key hashes.
 * The auth middleware caches valid API keys in AUTH_CACHE under
 * `auth:hash:${hash}`; when a key is revoked or its project deleted, those
 * entries must be removed so the revocation takes effect immediately instead
 * of waiting up to the 300s TTL. Fire-and-forget via waitUntil.
 */
export function invalidateAuthCacheEntries(c: AppContext, keyHashes: Iterable<string>): void {
  const cache = c.env.AUTH_CACHE;
  if (!cache) return;
  const hashes = Array.from(keyHashes);
  if (hashes.length === 0) return;
  c.executionCtx.waitUntil(Promise.all(hashes.map((hash) => cache.delete(`auth:hash:${hash}`))));
}

/**
 * Parse and validate an order query parameter ("asc" or "desc").
 * Defaults to "desc" if not provided or invalid.
 */
export function parseOrderParam(
  raw: string | undefined,
  defaultOrder: "asc" | "desc" = "desc",
): "asc" | "desc" {
  return raw === "asc" || raw === "desc" ? raw : defaultOrder;
}
